// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/category/add": {
            "post": {
                "description": "新しいカテゴリを登録する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "カテゴリ"
                ],
                "summary": "登録する",
                "operationId": "add-category",
                "parameters": [
                    {
                        "description": "crud:1(更新種別),name(カテゴリ名)",
                        "name": "newcategory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CategoryUpParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Category"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/category/byid/{id}": {
            "get": {
                "description": "指定されたカテゴリIDのカテゴリを取得する",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "カテゴリ"
                ],
                "summary": "取得する",
                "operationId": "get-category-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id(カテゴリID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Category"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/category/delete": {
            "delete": {
                "description": "指定された識別子でカテゴリを削除する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "カテゴリ"
                ],
                "summary": "削除する",
                "operationId": "delete-category",
                "parameters": [
                    {
                        "description": "crud:3(更新種別),id(カテゴリID)",
                        "name": "deletecategory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CategoryUpParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Category"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/category/list": {
            "get": {
                "description": "カテゴリ一覧を取得する",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "カテゴリ"
                ],
                "summary": "一覧を取得する",
                "operationId": "get-categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Category"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/category/update": {
            "put": {
                "description": "指定された識別子のカテゴリを変更する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "カテゴリ"
                ],
                "summary": "変更する",
                "operationId": "update-category",
                "parameters": [
                    {
                        "description": "crud:2(更新種別),id(カテゴリID),name(カテゴリ名)",
                        "name": "updatecategory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CategoryUpParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Category"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/product/add": {
            "post": {
                "description": "新商品を登録する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品"
                ],
                "summary": "登録する",
                "operationId": "add-product",
                "parameters": [
                    {
                        "description": "crud:1(更新種別),name(商品名),price(単価),categoryId(商品カテゴリ番号)",
                        "name": "newproduct",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ProductUpParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Product"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/product/byid/{id}": {
            "get": {
                "description": "指定された商品IDの商品を取得する",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品"
                ],
                "summary": "取得する",
                "operationId": "get-product-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id(商品ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Product"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/product/bykeyword/{keyword}": {
            "get": {
                "description": "指定されたキーワードが含まれる商品を取得する",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品"
                ],
                "summary": "取得する",
                "operationId": "get-product-by-keyword",
                "parameters": [
                    {
                        "type": "string",
                        "description": "キーワード",
                        "name": "keyword",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Product"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/product/delete": {
            "delete": {
                "description": "指定された識別子で商品を削除する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品"
                ],
                "summary": "削除する",
                "operationId": "delete-product",
                "parameters": [
                    {
                        "description": "crud:3(更新種別),id(商品ID)",
                        "name": "deleteproduct",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ProductUpParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Product"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/product/list": {
            "get": {
                "description": "商品一覧を取得する",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品"
                ],
                "summary": "一覧を取得する",
                "operationId": "get-products",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Product"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/product/liststream": {
            "get": {
                "description": "商品一覧を取得する",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品"
                ],
                "summary": "一覧を取得する(Server streaming RPC)",
                "operationId": "get-productstream",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Product"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/product/update": {
            "put": {
                "description": "指定された識別子の商品を変更する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品"
                ],
                "summary": "変更する",
                "operationId": "update-product",
                "parameters": [
                    {
                        "description": "crud:2(更新種別),id(商品ID),name(商品名),price(単価),categoryId(商品カテゴリ番号)",
                        "name": "updateproduct",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ProductUpParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Product"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.CRUD": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "CRUD_DELETE": "削除",
                "CRUD_INSERT": "追加",
                "CRUD_UNKNOWN": "不明",
                "CRUD_UPDATE": "変更"
            },
            "x-enum-varnames": [
                "CRUD_UNKNOWN",
                "CRUD_INSERT",
                "CRUD_UPDATE",
                "CRUD_DELETE"
            ]
        },
        "v1.Category": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "カテゴリ番号",
                    "type": "string"
                },
                "name": {
                    "description": "カテゴリ名",
                    "type": "string"
                }
            }
        },
        "v1.CategoryUpParam": {
            "type": "object",
            "properties": {
                "crud": {
                    "description": "更新の種類",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.CRUD"
                        }
                    ]
                },
                "id": {
                    "description": "商品カテゴリ番号",
                    "type": "string"
                },
                "name": {
                    "description": "商品カテゴリ名",
                    "type": "string"
                }
            }
        },
        "v1.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "エラーメッセージ",
                    "type": "string"
                },
                "type": {
                    "description": "エラー種別",
                    "type": "string"
                }
            }
        },
        "v1.Product": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "商品カテゴリ",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.Category"
                        }
                    ]
                },
                "id": {
                    "description": "商品Id",
                    "type": "string"
                },
                "name": {
                    "description": "商品名",
                    "type": "string"
                },
                "price": {
                    "description": "単価",
                    "type": "integer"
                }
            }
        },
        "v1.ProductUpParam": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "description": "商品カテゴリ番号",
                    "type": "string"
                },
                "crud": {
                    "description": "更新の種類",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.CRUD"
                        }
                    ]
                },
                "id": {
                    "description": "商品番号",
                    "type": "string"
                },
                "name": {
                    "description": "商品名",
                    "type": "string"
                },
                "price": {
                    "description": "単価",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "gRPCサンプルプログラム(CQRSサービス)",
	Description:      "カテゴリ情報と商品情報を管理するAPIサービス",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
